title: Soop Project
email: soopproject@gmail.com
description: "My knowledge library."
baseurl: ""
url: "http://soopproject.tk"
twitter_username: soopproject
github_username:  soopproject
minima: 
 date_format: "%b %-d, %Y"
markdown: kramdown
theme: minima
gems: 
 - jekyll-feed
